### ISSUE TITLE
[tracker] The godot-rust Book

### ISSUE THREAD

**Issue by ghost** [godot-rust/gdnative-book#1]
Over time, the godot-rust library grows, and the intricacies of the project can no longer fit in a simple README file. While there is the API documentation, it is very technical and hard to navigate for new users. The presence of [multiple](https://medium.com/@recallsingularity/gorgeous-godot-games-in-rust-1867c56045e6) [community-written](https://hagsteel.com/posts/godot-rust/) ["getting started" tutorials](https://github.com/tommywalkie/sample-godot-rust-app) is evidence that the learning curve is problematic and we really need an expanded user guide.

## Topics that should be covered

- [x] Detailed "getting started" tutorial (tracked in #4)
    - That should include instructions for installing Godot, Rust, and other dependencies.
- [x] Quick refresher of Godot's Scene/Node architecture
- [x] Overview of GDNative and the Godot scripting system, including the mechanisms of "inheritance" (#326)
    - [ ] Exposing "static" functions using autoloads and ZSTs (#380).
    - [ ] Detailed safety assumptions
- [ ] Using the official reference
- [ ] Replacing GDScript-specific APIs (`yield`, `preload`, etc.) (#400)
- [ ] Testing code that depends on the engine ("Godot tests")
- [ ] Instructions for exporting to mobile platforms (#238, godot-rust/godot-rust#285)
    - [x] Android (#335)
    - [ ] iOS
- [ ] MSVC vs GNU for Windows
- [ ] `Instance` downcasting API (frequently asked question, example issues: godot-rust/godot-rust#328, godot-rust/godot-rust#273, and a lot more) (tracked in #5)

## Contributing to the book

Since the book is still a very early work-in-progress and mostly blank, please leave a comment here before going ahead to write a section, to avoid duplication of work. PRs for the book should be made against the `book` branch, instead of `master`.

If there are other topics that you think should be covered in the book, please feel free to suggest them in the comments here.

- - -

Supersedes godot-rust/godot-rust#209.

**Comment by paytonrules** [comment]
As the book is in progress it could really use more explanation and examples around Ref/TRef and assume_safe and all it's variations. I'll give an example for clarification:

I'm moving my 0.8 code over to 0.9, and as part of my code I had a struct that held an Optional sprite, that's been changed to fit:

```
pub struct Enemy {
    sprite: Option<Ref<Sprite>>,
...
}
````

When I create the sprite I give it a name and assign it a texture at random from the resources. Unfortunately the entire function is still unsafe. At this time I create a mutable shared ref, and assume it's safe. After setting the texture I add the child, and then after it's added I save a reference - making sure to `claim` it. This compiles, huzzah, but I'm 99% sure it's wrong.

```
    #[export]
    unsafe fn _enter_tree(&mut self, owner: &Node2D) {
        /* ...  */ 
        let mut sprite = Sprite::new().into_shared().assume_safe();
        let sprite_name = /* irrelevant */
        let mut resource_loader = ResourceLoader::godot_singleton();
        let texture = /* irrelevant *

        sprite.set_texture(texture);
        owner.add_child(sprite, false);
        self.sprite = Some(sprite.claim());
    }
```

**Comment by ghost** [comment]
@paytonrules Acknowledged. If you need more information on `Ref` at this moment you can read the API documentation: https://docs.rs/gdnative/0.9.0-preview.0/gdnative/struct.Ref.html

As for the example code you have posted, you don't need to mark the entire function `unsafe`. You should only need it around `assume_safe`. Also the let binidngs don't need to be mutable anymore:

```rust
    #[export]
    fn _enter_tree(&mut self, owner: &Node2D) {
        /* ...  */ 
        let sprite = Sprite::new();
        let sprite_name = /* irrelevant */
        let resource_loader = ResourceLoader::godot_singleton();
        let texture = /* irrelevant */;

        sprite.set_texture(texture);

        let sprite = unsafe { sprite.into_shared().assume_safe() };
        owner.add_child(sprite, false);
        self.sprite = Some(sprite.claim());
    }
```

**Comment by paytonrules** [comment]
Thanks @toasteater -  I knew I didn't need the function unsafe, I just wanted to post it up before I forgot.

Is this still the best place for suggestions for the book? Or should there be new issues?

**Comment by ghost** [comment]
@paytonrules It might be better to open new issues now that we have a separate repo!
